### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by armic**
Fixed some CSS

@adamdom

### CODE REVIEW

**Comment by adelq** [comment]
Code looks fine. With design changes, prefer to have screenshots if possible, but this looks minor enough to not warrant one. Thanks!

Note: I have not personally tested this yet, so holding off on the official "LGTM"
Note 2: This comment was written for up to commit b37bc5dcf3a7cc16d8fcdd2fd47a5510fa7faabb, have not reviewed the rest.

**Comment by armic** [comment]
Okay, I'll remember to include those next time.  Thanks!

**Comment by adamdom** [comment]
Same as Adel. Will look at it during the meeting tonight.

**Comment by adamdom** [comment]
So the only thing I think we need to do is add the footer back on the homepage. I was actually thinking of deleting it on every page but index. It never lines up well on the other pages and it just isnt worth it. Plus the UA wants their logo on the main page.

**Comment by armic** [comment]
I actually ended up moving it to just a div and put both logos in the green box.  I'll show you it next time I see you

**Pull request merged**
